TicariOtomasyon/Models/Siniflar/Personel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TicariOtomasyon.Models.Siniflar
{
    public class Personel
    {
        [Key]
        public int Personelid { get; set; }

        [Display(Name="Personel Adı")]
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string PersonelAd { get; set; }
        [Display(Name = "Personel Soyadı")]
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string PersonelSoyad { get; set; }
        [Display(Name = "Personel Görsel")]
        [Column(TypeName = "Varchar")]
        [StringLength(250)]
        public string PersonelGorsel { get; set; }

        public ICollection<SatisHareket> SatisHarekets { get; set; }
        public int Departmanid { get; set; }
        public virtual Departman Departman { get; set; } 

    }
}

TicariOtomasyon/Controllers/PersonelController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls.WebParts;
using TicariOtomasyon.Models.Siniflar;

namespace TicariOtomasyon.Controllers
{
    public class PersonelController : Controller
    {
        Context c=new Context();
        // GET: Personel
        public ActionResult Index()
        {
            var degerler=c.Personels.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult PersonelEkle() {
            List<SelectListItem> deger1 = (from x in c.Departmans.ToList() select new SelectListItem { Text = x.DepartmanAd, Value = x.Departmanid.ToString() }).ToList();
            ViewBag.dgr1 = deger1;
            
            return View();
        }
        [HttpPost]
        public ActionResult PersonelEkle(Personel personel)
        {
            if (Request.Files.Count > 0)
            {
                string dosyaadi = Path.GetFileName(Request.Files[0].FileName);
                string uzanti = Path.GetExtension(Request.Files[0].FileName);
                string yol = "~/Images/"+dosyaadi+uzanti;
                Request.Files[0].SaveAs(Server.MapPath(yol));
                personel.PersonelGorsel = "/Images/" + dosyaadi + uzanti;
            }

            //if (!ModelState.IsValid)
            //{ return View(); }
            c.Personels.Add(personel);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult PersonelGetir(int id)
        {    
            
            List<SelectListItem> deger1 = (from x in c.Departmans.ToList() select new SelectListItem { Text = x.DepartmanAd, Value = x.Departmanid.ToString() }).ToList();
            ViewBag.dgr1=deger1;
            var personel = c.Personels.Find(id);
            return View("PersonelGetir", personel);
        }
        public ActionResult PersonelGuncelle(Personel per)
        {

            if (Request.Files.Count > 0)
            {
                string dosyaadi = Path.GetFileName(Request.Files[0].FileName);
                string uzanti = Path.GetExtension(Request.Files[0].FileName);
                string yol = "~/Images/" + dosyaadi + uzanti;
                Request.Files[0].SaveAs(Server.MapPath(yol));
                per.PersonelGorsel = "/Images/" + dosyaadi + uzanti;
            }

            if (!ModelState.IsValid) { return View("PersonelGetir"); }
            var personel = c.Personels.Find(per.Personelid);
            personel.Personelid = per.Personelid;
            personel.PersonelAd = per.PersonelAd;
            personel.PersonelSoyad = per.PersonelSoyad;
            personel.PersonelGorsel = per.PersonelGorsel;
            personel.Departmanid = per.Departmanid;
            c.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult PersonelListesi() {
            var degerler = c.Personels.ToList();
            return View(degerler); 
        }
    }
}

TicariOtomasyon/Views/Personel/Index.cshtml
@using TicariOtomasyon.Models.Siniflar
@model List<Personel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Index</h2>

<table class="table table-bordered">
    <tr>
        <th>Personel id</th>
        <th>Personel Adı</th>
        <th>Personel Soyadı</th>
        <th>Personel Gorsel</th>
        <th>Departman</th>
        <th>Güncelle</th>
        <th>Detaylar</th>
    </tr>
    @foreach (var per in Model)
    {
        <tr>
            <td>@per.Personelid</td>           
            <td>@per.PersonelAd</td>         
            <td>@per.PersonelSoyad</td>         
            <td><img src="@per.PersonelGorsel" style="width:75px;height:50px"/></td>       
            <td>@per.Departman.DepartmanAd</td>       
            <td><a href="~/Personel/PersonelGetir/@per.Personelid" class="btn btn-warning">Güncele</a></td>
            <td><a href="~/Departman/DepartmanPersonelSatis/@per.Personelid" class="btn btn-default" style="background-color:lightcoral">Satış Geçmişi</a></td>
        </tr>
    }
</table>
<a href="/Personel/PersonelEkle" class="btn btn-primary">Yeni Personel</a>

TicariOtomasyon/Views/Personel/PersonelEkle.cshtml
@model TicariOtomasyon.Models.Siniflar.Personel
@{
    ViewBag.Title = "PersonelEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>PersonelEkle</h2>

@using (Html.BeginForm("PersonelEkle", "Personel", FormMethod.Post, new { enctype = "multipart/form-data" })) { 
    <form class="form-group" method="post">
        <br />
        @Html.LabelFor(x => x.PersonelAd) @Html.TextBoxFor(x => x.PersonelAd, new { @class = "form-control" }) <br />
        @Html.LabelFor(x => x.PersonelSoyad) @Html.TextBoxFor(x => x.PersonelSoyad, new { @class = "form-control" }) <br />
        @Html.LabelFor(x => x.PersonelGorsel)  <br /> <input type="file" name="PersonelGorsel" />   <br /><br />
        @Html.LabelFor(x => x.Departman.Departmanid, "Personel Departman:") @Html.DropDownListFor(x => x.Departmanid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })

        <br />
        <button class=" btn btn-info">Kaydet</button>


    </form>
}

TicariOtomasyon/Views/Personel/PersonelGetir.cshtml
@model TicariOtomasyon.Models.Siniflar.Personel
@{
    ViewBag.Title = "PersonelGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>PersonelGetir</h2>


@using (Html.BeginForm("PersonelGuncelle", "Personel", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.Personelid)
        @Html.LabelFor(x => x.PersonelAd) @Html.TextBoxFor(x => x.PersonelAd, new { @class = "form-control" })
        @Html.LabelFor(x => x.PersonelSoyad) @Html.TextBoxFor(x => x.PersonelSoyad, new { @class = "form-control" })
        @Html.LabelFor(x => x.PersonelGorsel)  <br /> <input type="file" name="PersonelGorsel" />   <br /><br />
        @Html.LabelFor(x => x.Departmanid, "Personel Departman: ")  @Html.DropDownListFor(x => x.Departmanid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    </div>
    <button class="btn btn-warning">Güncelle</button>
}

TicariOtomasyon/Views/Personel/PersonelListesi.cshtml
@using TicariOtomasyon.Models.Siniflar
@model List<Personel>
@{
    ViewBag.Title = "PersonelListesi";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";


}

<h2>Personel Listesi</h2>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Contacts</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
            <!-- Main content -->
            <section class="content">

                <!-- Default box -->
                <div class="card card-solid">
                    <div class="card-body pb-0">
                        <div class="row d-flex align-items-stretch">
                            @foreach (var x in Model)
                            {
                                <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">

                                    <div class="card bg-light">
                                        <div class="card-header text-muted border-bottom-0">
                                            @x.Departman.DepartmanAd
                                        </div>
                                        <div class="card-body pt-0">

                                            <div class="row">
                                                <div class="col-7">
                                                    <h2 class="lead"><b>@x.PersonelAd @x.PersonelSoyad</b></h2>
                                                    <p class="text-muted text-sm"><b>About: </b> Web Designer / UX / Graphic Artist / Coffee Lover </p>
                                                    <ul class="ml-4 mb-0 fa-ul text-muted">
                                                        <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Address: Demo Street 123, Demo City 04312, NJ</li>
                                                        <li class="small"><span class="fa-li"><i class="fas fa-lg fa-phone"></i></span> Phone #: + 800 - 12 12 23 52</li>
                                                    </ul>
                                                </div>
                                                <div class="col-5 text-center">
                                                    <img src="@x.PersonelGorsel" alt="" class="img-circle img-fluid">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="card-footer">
                                            <div class="text-right">
                                                <a href="/Personel/PersonelGetir/@x.Personelid" class="btn btn-sm bg-teal">
                                                    <i class="fas fa-comments"></i>
                                                </a>
                                                <a href="/Departman/DepartmanPersonelSatis/@x.Personelid" class="btn btn-sm btn-primary">
                                                    <i class="fas fa-user"></i> View Profile
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                    
                                </div>
                            }
                        </div>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                        <nav aria-label="Contacts Page Navigation">
                            <ul class="pagination justify-content-center m-0">
                                <li class="page-item active"><a class="page-link" href="#">1</a></li>
                                <li class="page-item"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item"><a class="page-link" href="#">4</a></li>
                                <li class="page-item"><a class="page-link" href="#">5</a></li>
                                <li class="page-item"><a class="page-link" href="#">6</a></li>
                                <li class="page-item"><a class="page-link" href="#">7</a></li>
                                <li class="page-item"><a class="page-link" href="#">8</a></li>
                            </ul>
                        </nav>
                    </div>
                    <!-- /.card-footer -->
                </div>
                <!-- /.card -->

            </section>
            <!-- /.content -->

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>
</body>
</html>