TicariOtomasyon/Controllers/FaturaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using TicariOtomasyon.Models.Siniflar;


namespace TicariOtomasyon.Controllers
{
    public class FaturaController : Controller
    {
        Context c=new Context();
        // GET: Fatura
        public ActionResult Index()
        {
            var faturalar = c.Faturalars.ToList();
            return View(faturalar);
        }
        [HttpGet]
        public ActionResult FaturaEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult FaturaEkle(Faturalar f)
        {
            c.Faturalars.Add(f);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult FaturaGetir(int id) {
            var fatura=c.Faturalars.Find(id);
            return View(fatura);
        }
        public ActionResult FaturaGuncelle(Faturalar f)
        {
            var fatura = c.Faturalars.Find(f.Faturaid);
            fatura.FaturaSıraNo = f.FaturaSıraNo;
            fatura.FaturaSeriNo = f.FaturaSeriNo;
            fatura.Tarih=f.Tarih;
            fatura.Saat = f.Saat;
            fatura.TeslimAlan=f.TeslimAlan;
            fatura.TeslimEden = f.TeslimEden;
            fatura.Toplam=f.Toplam;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult FaturaDetay(int id)
        {
            var faturak=c.FaturaKalems.Where(f=>f.Faturaid==id).ToList();
            return View(faturak);
        }

        [HttpGet]
        public ActionResult YeniKalem() { return View(); }
        [HttpPost]
        public ActionResult YeniKalem(FaturaKalem fk) { 
            c.FaturaKalems.Add(fk);
            c.SaveChanges();
            return RedirectToAction("Index"); }

        public ActionResult DinamikFatura() { 
            DinamikFaturaClass dmk=new DinamikFaturaClass();
            dmk.deger1 = c.Faturalars.ToList();
            dmk.deger2=c.FaturaKalems.ToList();
            return View(dmk); }

        public ActionResult FaturaKaydet(string FaturaSeriNo, string FaturaSıraNo, DateTime Tarih , string VergiDairesi,
            string Saat, string TeslimEden, string TeslimAlan, string Toplam, FaturaKalem[] kalemler)
        {
            Faturalar f=new Faturalar();
            f.FaturaSeriNo = FaturaSeriNo;
            f.FaturaSıraNo = FaturaSıraNo;
            f.Tarih = Tarih;
            f.VergiDairesi= VergiDairesi;
            f.Saat = Saat;
            f.TeslimEden= TeslimEden;
            f.TeslimAlan = TeslimAlan;
            f.Toplam = decimal.Parse(Toplam);
            c.Faturalars.Add(f);
            foreach(var x in kalemler)
            {
                FaturaKalem fk=new FaturaKalem();
                fk.Aciklama = x.Aciklama;
                fk.BirimFiyat= x.BirimFiyat;
                fk.Faturaid= x.Faturaid;
                fk.Miktar= x.Miktar;
                fk.Tutar= x.Tutar;
                c.FaturaKalems.Add(fk);
            }
            c.SaveChanges();
            return Json("İşlem Başarılı",JsonRequestBehavior.AllowGet);
        }

    }
} 

TicariOtomasyon/Controllers/KategoriController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TicariOtomasyon.Models.Siniflar;

namespace TicariOtomasyon.Controllers
{ [Authorize]
    public class KategoriController : Controller
    {
        // GET: Kategori
        
        Context c= new Context();
       
        public ActionResult Index(int sayfa=1)
        {
            var degerler=c.Kategoris.ToList().ToPagedList(sayfa,8);
            return View(degerler);
        }

        [HttpGet]
        public ActionResult KategoriEkle() { return View(); }
        [HttpPost]
        public ActionResult KategoriEkle(Kategori k) {
            c.Kategoris.Add(k);
            c.SaveChanges();
            return RedirectToAction("Index"); 
        }
        public ActionResult KategoriSil(int id ) {
            var ktg=c.Kategoris.Find(id);
            c.Kategoris.Remove(ktg);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult KategoriGetir(int id)
        {
            var kategori=c.Kategoris.Find(id);
            return View("KategoriGetir",kategori);
        }
        public ActionResult KategoriGuncelle(Kategori k)
        {
            var ktgr = c.Kategoris.Find(k.KategoriID);
            ktgr.KategoriAd = k.KategoriAd;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult KategoriAlt()
        {
            AltDegerSinif dgr= new AltDegerSinif();
            dgr.Kategoriler = new SelectList(c.Kategoris, "KategoriID", "KategoriAd");
            dgr.Urunler = new SelectList(c.Uruns, "UrunID", "UrunAd");
            return View(dgr);
        }
        public JsonResult UrunGetir(int p)
        {
            var urunListesi=(from x in c.Uruns
                             join y in c.Kategoris
                             on x.Kategori.KategoriID equals y.KategoriID
                             where x.Kategori.KategoriID== p
                             select new
                             {
                                 Text=x.UrunAdi,
                                 Value=x.Urunid.ToString()
                             }).ToList();
            return Json(urunListesi,JsonRequestBehavior.AllowGet);
        }
    }
}

TicariOtomasyon/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>MVC5 Ticari Otomasyon</title>
    <link href="~/Web/dist/css/styles.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="index.html">Ticari Otomasyon</a><button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button><!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Aranacak kelime..." aria-label="Search" aria-describedby="basic-addon2" />
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#">Ayarlar</a><a class="dropdown-item" href="#">Hesabım</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="login.html">Çıkış Yap</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">İşlemler</div>
                        <a class="nav-link" href="~/Kategori/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Kategoriler
                        </a>
                        <a class="nav-link" href="~/Urun/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-flask"></i></div>
                            Ürünler
                        </a>
                        <a class="nav-link" href="~/Departman/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-bars"></i></div>
                            Departmanlar
                        </a>
                        <a class="nav-link" href="~/Cari/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-user"></i></div>
                            Cariler
                        </a>
                        <a class="nav-link" href="~/Personel/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-street-view"></i></div>
                            Personeller
                        </a>
                        <a class="nav-link" href="~/Personel/PersonelTablosu">
                            <div class="sb-nav-link-icon"><i class="fas fa-percent"></i></div>
                            Personel Tablosu
                        </a>

                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Grafikler
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                    Grafik Türleri
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="~/Grafik/Index3">Sütun</a>
                                        <a class="nav-link" href="~/Grafik/Index4">Pasta</a>
                                        <a class="nav-link" href="~/Grafik/Index6">Çizgi</a>
                                    </nav>
                                </div>
                                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                    Hata Sayfaları
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav"><a class="nav-link" href="401.html">401 Page</a><a class="nav-link" href="404.html">404 Page</a><a class="nav-link" href="500.html">500 Page</a></nav>
                                </div>
                            </nav>
                        </div>

                        <div class="sb-sidenav-menu-heading">Rapor & Fatura</div>
                        <a class="nav-link" href="~/Satis/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-taxi"></i></div>
                            Satışlar
                        </a>
                        <a class="nav-link" href="~/Fatura/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-calendar"></i></div>
                            Faturalar
                        </a>
                        <a class="nav-link" href="~/Fatura/DinamikFatura">
                            <div class="sb-nav-link-icon"><i class="fas fa-address-card"></i></div>
                            Dinamik Faturalar
                        </a>
                        <a class="nav-link" href="index.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-plane"></i></div>
                            Fatura Kalemler
                        </a>
                        <a class="nav-link" href="index.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-gift"></i></div>
                            Giderler
                        </a>
                        <a class="nav-link" href="~/Urun/UrunListesi">
                            <div class="sb-nav-link-icon"><i class="fas fa-print"></i></div>
                            Pdf & Excel
                        </a>
                        <a class="nav-link" href="~/Alertler/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-box"></i></div>
                            Alertler
                        </a>
                        <a class="nav-link" href="~/Istatistik/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-database"></i></div>
                            İstatistikler
                        </a>
                        <a class="nav-link" href="~/Galeri/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-camera"></i></div>
                            Galeri
                        </a> <a class="nav-link" href="~/UrunDetay/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-shopping-bag"></i></div>
                            Ürün Detay
                        </a>
                        @if (User.IsInRole("1"))
                        {
                            <a class="nav-link" href="~/Istatistik/SimpleTables">
                                <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                                Hızlı Bakış Tabloları
                            </a>
                        }
                        <a class="nav-link" href="~/Kargo/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-gifts"></i></div>
                            Kargolar
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </main>
          
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2019</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/Web/dist/js/scripts.js"></script>
</body>
</html>

TicariOtomasyon/Views/Shared/_CariLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap core CSS -->
    <link href="~/webpanel/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="~/webpanel/css/simple-sidebar.css" rel="stylesheet">

</head>

<body>

    <div class="d-flex" id="wrapper">

        <!-- Sidebar -->
        <div class="bg-light border-right" id="sidebar-wrapper">
            <div class="sidebar-heading">Cari Panel</div>
            <div class="list-group list-group-flush">
                <a href="/CariPanel/Index" class="list-group-item list-group-item-action bg-light">Profilim</a>
                <a href="/CariPanel/Siparislerim" class="list-group-item list-group-item-action bg-light">Siparişlerim</a>
                <a href="/Cari/KargoTakip" class="list-group-item list-group-item-action bg-light">Kargo Takibi</a>
                <a href="/CariPanel/GelenMesaj" class="list-group-item list-group-item-action bg-light">Mesajlar</a>
                <a href="/CariPanel/LogOut" class="list-group-item list-group-item-action bg-light">Çıkış Yap</a>
            </div>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        <div id="page-content-wrapper">

            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                <button class="btn btn-primary" id="menu-toggle">Menu</button>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Profilim <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Kargom nerede</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Menü
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="#">Siparişlerim</a>
                                <a class="dropdown-item" href="#">Yardım</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="/CariPanel/LogOut">Çıkış yap</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>

            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
        <!-- /#page-content-wrapper -->
       
    </div>
    <!-- /#wrapper -->
    <!-- Bootstrap core JavaScript -->
    <script src="~/webpanel/vendor/jquery/jquery.min.js"></script>
    <script src="~/webpanel/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>$("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });</script>

</body>

</html>

TicariOtomasyon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Fatura İşlemleri ", "DinamikFatura", "Fatura", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Faturalar", "DinamikFatura", "Fatura")</li>
                    <li>@Html.ActionLink("Admin", "Index", "Kategori")</li>
                    <li>@Html.ActionLink("Yardım", "Yardim", "Admin")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>