TicariOtomasyon/Models/Siniflar/KargoTakip.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TicariOtomasyon.Models.Siniflar
{
    public class KargoTakip
    {
        [Key]
        public int KargoTakipid { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(10)]
        public string TakipKodu { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(100)]

        public string Aciklama { get; set; }
        public DateTime TarihZaman { get; set; }
    }
}

TicariOtomasyon/Controllers/KargoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TicariOtomasyon.Models.Siniflar;

namespace TicariOtomasyon.Controllers
{
    public class KargoController : Controller
    {
        // GET: Kargo
        Context c = new Context();
        public ActionResult Index(string a)
        {
            var kar = from x in c.KargoDetays select x;
            if (!string.IsNullOrEmpty(a))
            {
                kar = kar.Where(x => x.TakipKodu.Contains(a));
            }
            return View(kar.ToList());
            
        }
        [HttpGet]
        public ActionResult YeniKargo() {
            Random rnd = new Random();
            string[] karakterler = { "A", "B", "C", "D" };
            int k1, k2, k3;
            k1=rnd.Next(0,4);
            k2=rnd.Next(0,4);
            k3=rnd.Next(0,4);
            int s1, s2, s3;
            s1=rnd.Next(100,1000);
            s2=rnd.Next(10,100);
            s3=rnd.Next(10,100);
            string kod = s1.ToString() + karakterler[k1] + s2.ToString() + karakterler[k2] + s3.ToString() + karakterler[k3];
            ViewBag.takipkodu = kod;
            return View(); 
        }
        [HttpPost]
        public ActionResult YeniKargo(KargoDetay kd)
        {
            c.KargoDetays.Add(kd);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult KargoTakip(string id)
        {
            var ktakip = c.KargoTakips.Where(x=>x.TakipKodu==id).ToList();
            return View(ktakip);
        }
    }
}

TicariOtomasyon/Views/Kargo/Index.cshtml
@using TicariOtomasyon.Models.Siniflar
@model List<KargoDetay>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
@using (Html.BeginForm("Index", "Kargo", FormMethod.Get))
{
    <p>Kargo Takip kodu: @Html.TextBox("a") <input type="submit" value="Ara" name="takipKodu" /></p>
}
<br />
<table class="table table-bordered">
    <tr>
        <th>Personel</th>
        <th>Alıcı</th>
        <th>Takip Kodu</th>
        <th>Tarih</th>
        <th>Detaylar</th>
    </tr>

    @foreach (var k in Model)
    {
        <tr>
            <td>@k.Personel</td>
            <td>@k.Alici</td>
            <td>@k.TakipKodu</td>
            <td>@k.Tarih</td>
            
            <td><a href="/Kargo/KargoTakip/@k.TakipKodu" class="btn btn-default" style="background-color:lightcoral">Detay</a></td>
        </tr>
    }

</table>
<a href="/Kargo/YeniKargo" class="btn btn-primary">Yeni Kargo Girişi</a>

TicariOtomasyon/Views/Kargo/KargoTakip.cshtml
@using TicariOtomasyon.Models.Siniflar
@model List<KargoTakip>
@{
    ViewBag.Title = "KargoTakip";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>KargoTakip</h2>


<table class="table table-hover">
    <tr>

        <th>Takip Kodu</th>
        <th>Açıklama</th>
        <th>Tarih</th>
       
    </tr>
    @foreach (var kt in Model)
    {
        <tr>
            <td>@kt.TakipKodu</td>
            <td>@kt.Aciklama</td>
            <td>@kt.TarihZaman</td>

        </tr>
    }
</table>

TicariOtomasyon/Views/Kargo/YeniKargo.cshtml
@model TicariOtomasyon.Models.Siniflar.KargoDetay

@{
    ViewBag.Title = "YeniKargo";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>YeniKargo</h2>

<form class="form-group" method="post">
    <br />
    @Html.LabelFor(x => x.TakipKodu) <input type="text" name="TakipKodu" value="@ViewBag.takipkodu" class="form-control" readonly/>
    @Html.LabelFor(x => x.Personel) @Html.TextBoxFor(x => x.Personel, new { @class = "form-control" })
    @Html.LabelFor(x => x.Alici) @Html.TextBoxFor(x => x.Alici, new { @class = "form-control" })
    @Html.LabelFor(x => x.Tarih) <input type="date" name="Tarih" placeholder="Tarih Giriniz" class="form-control"/>
    @Html.LabelFor(x => x.Aciklama) @Html.TextAreaFor(x => x.Aciklama, new { @class = "form-control" })
    <br />
    <button class=" btn btn-info">Kaydet</button>
</form>