TicariOtomasyon/Controllers/SatisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TicariOtomasyon.Models.Siniflar;

namespace TicariOtomasyon.Controllers
{
    public class SatisController : Controller
    {
        Context c = new Context();
        // GET: Satis
        public ActionResult Index()
        {
            var degerler=c.SatisHarekets.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult YeniSatis() {
            List<SelectListItem> deger1 = (from x in c.Uruns.ToList() select new SelectListItem { Text = x.UrunAdi, Value = x.Urunid.ToString() }).ToList();
            List<SelectListItem> deger2 = (from x in c.Carilers.ToList() select new SelectListItem { Text = x.CariAd+" "+x.CariSoyad, Value = x.Cariid.ToString() }).ToList();
            List<SelectListItem> deger3 = (from x in c.Personels.ToList() select new SelectListItem { Text = x.PersonelAd, Value = x.Personelid.ToString() }).ToList();
            ViewBag.dgr1 = deger1;
            ViewBag.dgr2 = deger2;
            ViewBag.dgr3 = deger3;

            return View(); }
        [HttpPost]
        public ActionResult YeniSatis(SatisHareket satis) { 
            satis.Tarih=DateTime.Parse(DateTime.Now.ToShortDateString());
            c.SatisHarekets.Add(satis);
            c.SaveChanges();
            return RedirectToAction("Index"); 
        }
        public ActionResult SatisGetir(int id) {
            List<SelectListItem> deger1 = (from x in c.Uruns.ToList() select new SelectListItem { Text = x.UrunAdi, Value = x.Urunid.ToString() }).ToList();
            List<SelectListItem> deger2 = (from x in c.Carilers.ToList() select new SelectListItem { Text = x.CariAd + " " + x.CariSoyad, Value = x.Cariid.ToString() }).ToList();
            List<SelectListItem> deger3 = (from x in c.Personels.ToList() select new SelectListItem { Text = x.PersonelAd, Value = x.Personelid.ToString() }).ToList();
            ViewBag.dgr1 = deger1;
            ViewBag.dgr2 = deger2;
            ViewBag.dgr3 = deger3;

            var satisdeger = c.SatisHarekets.Find(id);
            return View("SatisGetir", satisdeger);
        }

        public ActionResult SatisGuncelle(SatisHareket s) {
            var deger = c.SatisHarekets.Find(s.Satisid);
            deger.Cariid = s.Cariid; 
            deger.Personelid = s.Personelid;
            deger.Adet = s.Adet;
            deger.Fiyat = s.Fiyat;
            deger.Urunid= s.Urunid;
            deger.ToplamTutar = s.ToplamTutar;
            deger.Tarih= s.Tarih;
            c.SaveChanges();
            return RedirectToAction("Index"); 
        }
        public ActionResult SatisDetay(int id)
        {
            var deger = c.SatisHarekets.Where(x => x.Satisid == id).ToList();

            return View(deger);
        }
    }
}

TicariOtomasyon/Views/Satis/Index.cshtml
@using TicariOtomasyon.Models.Siniflar
@model List<SatisHareket>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Index</h2>

<table id="SatisTable" class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Ürün</th>
            <th>Cari</th>
            <th>Personel</th>
            <th>Adet</th>
            <th>Fiyat</th>
            <th>Toplam</th>
            <th>Tarih</th>
            <th>Güncelle</th>
            <th>Detaylar</th>
        </tr>
    </thead>
    @foreach (var sh in Model)
    {
        <tr>
            <td>@sh.Satisid</td>
            <td>@sh.Urun.UrunAdi</td>
            <td>@sh.Cariler.CariAd @sh.Cariler.CariSoyad</td>
            <td>@sh.Personel.PersonelAd @sh.Personel.PersonelSoyad</td>
            <td>@sh.Adet</td>
            <td>@sh.Fiyat</td>
            <td>@sh.ToplamTutar</td>
            <td>@sh.Tarih</td>
            <td><a href="~/Satis/SatisGetir/@sh.Satisid" class="btn btn-warning">Güncelle</a></td>
            <td><a href="~/Satis/SatisDetay/@sh.Satisid" class="btn btn-default" style="background-color:lightcoral">Detay</a></td>
        </tr>
    }
</table>
<a href="/Satis/YeniSatis" class="btn btn-primary">Satış Yap</a>



@*<link href="~/Content/bootstrap.css" rel="stylesheet" />*@

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />

<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />

<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>

<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>

<script>

    $('#SatisTable').dataTable({});

</script>

TicariOtomasyon/Views/Satis/SatisDetay.cshtml
@using TicariOtomasyon.Models.Siniflar
@model  List<SatisHareket>
@{
    ViewBag.Title = "SatisDetay";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Satış Detay</h2>
<br />
@*<ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active">Personel Adı: @ViewBag.bagPers</li>
    </ol>*@

<table class="table table-hover">
    <tr>
        <th>Satış ID</th>
        <th>Ürün Adı</th>
        <th>Cari</th>
        <th>Personel</th>
        <th>Fiyat</th>
        <th>Toplam Tutar</th>
        <th>Tarih</th>

        @*<th>Yazdır</th>*@

    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.Satisid</td>
            <td>@x.Urun.UrunAdi</td>
            <td>@x.Cariler.CariAd @x.Cariler.CariSoyad</td>
            <td>@x.Personel.PersonelAd @x.Personel.PersonelSoyad</td>
            <td>@x.Fiyat</td>
            <td>@x.ToplamTutar</td>
            <td>@x.Tarih</td>
            @*<td><a class="btn btn-primary " href="#">Yazdır</a></td>*@

        </tr>
    }

</table>

<button class="btn btn-primary">Yazdır</button>

TicariOtomasyon/Views/Satis/SatisGetir.cshtml
@model TicariOtomasyon.Models.Siniflar.SatisHareket
@{
    ViewBag.Title = "SatisGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Satış Güncelleme Sayfası</h2>


@using (Html.BeginForm("SatisGuncelle", "Satis", FormMethod.Post))
{
    @Html.HiddenFor(x => x.Satisid)
    @Html.LabelFor(x => x.Urun, "Urun") @Html.DropDownListFor(x => x.Urunid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    @Html.LabelFor(x => x.Cariler, "Cari") @Html.DropDownListFor(x => x.Cariid, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    @Html.LabelFor(x => x.Personel, "Personel") @Html.DropDownListFor(x => x.Personelid, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
    @Html.LabelFor(x => x.Adet, "Adet:") @Html.TextBoxFor(x => x.Adet, new { @class = "form-control" })
    @Html.LabelFor(x => x.Fiyat, "Fiyat:") @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
    @Html.LabelFor(x => x.ToplamTutar, "Toplam Tutar:") @Html.TextBoxFor(x => x.ToplamTutar, new { @class = "form-control" })
    @Html.LabelFor(x => x.Tarih, "Tarih:") @Html.TextBoxFor(x => x.Tarih, new { @class = "form-control" })
    @*@Html.LabelFor(x => x.Kategori.KategoriID, "Ürün Kategori:") @Html.DropDownListFor(x => x.Kategoriid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })*@
    <br />
    <button class=" btn btn-warning">Kaydet</button>
}

TicariOtomasyon/Views/Satis/YeniSatis.cshtml
@model  TicariOtomasyon.Models.Siniflar.SatisHareket
@{
    ViewBag.Title = "YeniSatis";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Yeni Satış Sayfası</h2>


<form class="form-group" method="post">
    <br />
    @Html.LabelFor(x => x.Urun, "Urun") @Html.DropDownListFor(x => x.Urunid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    @Html.LabelFor(x => x.Cariler, "Cari") @Html.DropDownListFor(x => x.Cariid, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    @Html.LabelFor(x => x.Personel, "Personel") @Html.DropDownListFor(x => x.Personelid, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
    @Html.LabelFor(x => x.Adet, "Adet") @Html.TextBoxFor(x => x.Adet, new { @class = "form-control" })
    @Html.LabelFor(x => x.Fiyat, "Fiyat") @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
    @Html.LabelFor(x => x.ToplamTutar, "Toplam Tutar") @Html.TextBoxFor(x => x.ToplamTutar, new { @class = "form-control" })

    <br />
    <button class=" btn btn-info">Kaydet</button>


</form>